//
//  HomePresenter.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter {
    //MARK: - Protocol Properties
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    //MARK: - Life Cycle
    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomePresenter: HomePresenterProtocol {
    func favoriteVC() {
        router.favoriteVC()
    }
    
    func deleteVC() {
        router.deleteVC()
    }
    
    func spamVC() {
        router.spamVC()
    }
    
    
    func getListEmail() {
        interactor?.getListEmail()
    }
    
    func infoEmail(data: Results) {
        view?.infoEmail(data: data)
    }
    
    
}

//MARK: - Private functions
extension HomePresenter {
    
}
