//
//  DeleteMessagePresenter.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DeleteMessagePresenter {
    //MARK: - Protocol Properties
    weak private var view: DeleteMessageViewProtocol?
    var interactor: DeleteMessageInteractorProtocol?
    private let router: DeleteMessageWireframeProtocol

    //MARK: - Life Cycle
    init(interface: DeleteMessageViewProtocol, interactor: DeleteMessageInteractorProtocol?, router: DeleteMessageWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension DeleteMessagePresenter: DeleteMessagePresenterProtocol {
    func infoEmail(data: Results) {
        view?.infoEmail(data: data)
    }
    
    func getListEmail() {
        interactor?.getListEmail()
    }
    
    
}

//MARK: - Private functions
extension DeleteMessagePresenter {
    
}
