//
//  DeleteMessageViewController.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DeleteMessageViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: DeleteMessagePresenterProtocol?

    //MARK: - Properties
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .red
    }
    
    //MARK: - Methods
}

//MARK: - View Methods
extension DeleteMessageViewController: DeleteMessageViewProtocol {
    
}

//MARK: - Private functions
extension DeleteMessageViewController {
    
}
