//
//  DeleteMessageInteractor.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DeleteMessageInteractor {
    //MARK: - Protocol Properties
    weak var presenter: DeleteMessagePresenterProtocol?
}

//MARK: - Interactor Methods
extension DeleteMessageInteractor: DeleteMessageInteractorProtocol {
    
}
