//
//  DeleteMessageProtocols.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DeleteMessageWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol DeleteMessagePresenterProtocol: AnyObject {
    func infoEmail(data: Results)
    func getListEmail()
}

//MARK: Interactor -
protocol DeleteMessageInteractorProtocol: AnyObject {
    func getListEmail()
  var presenter: DeleteMessagePresenterProtocol?  { get set }
}

//MARK: View -
protocol DeleteMessageViewProtocol: AnyObject {
    func infoEmail(data: Results)
  var presenter: DeleteMessagePresenterProtocol?  { get set }
}
