//
//  SpamMessageViewController.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SpamMessageViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: SpamMessagePresenterProtocol?

    //MARK: - Properties
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .blue
    }
    
    //MARK: - Methods
}

//MARK: - View Methods
extension SpamMessageViewController: SpamMessageViewProtocol {
    
}

//MARK: - Private functions
extension SpamMessageViewController {
    
}
