//
//  SpamMessageProtocols.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SpamMessageWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol SpamMessagePresenterProtocol: AnyObject {
    func getListEmail()
    func infoEmail(data: Results)
}

//MARK: Interactor -
protocol SpamMessageInteractorProtocol: AnyObject {
    func getListEmail()
  var presenter: SpamMessagePresenterProtocol?  { get set }
}

//MARK: View -
protocol SpamMessageViewProtocol: AnyObject {
    func infoEmail(data: Results)
  var presenter: SpamMessagePresenterProtocol?  { get set }
}
