//
//  SpamMessageRouter.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SpamMessageRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SpamMessageViewController(nibName: nil, bundle: nil)
        let interactor = SpamMessageInteractor()
        let router = SpamMessageRouter()
        let presenter = SpamMessagePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

//MARK: - Router Metods
extension SpamMessageRouter: SpamMessageWireframeProtocol {
    
}

//MARK: - Private functions
extension SpamMessageRouter {
    
}
