//
//  SpamMessageInteractor.swift
//  Evaluacion_Stefanini
//
//  Created Administrator on 04/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SpamMessageInteractor {
    //MARK: - Protocol Properties
    weak var presenter: SpamMessagePresenterProtocol?
}

//MARK: - Interactor Methods
extension SpamMessageInteractor: SpamMessageInteractorProtocol {
    
}
